services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DB_TYPE=${DB_TYPE:-mock}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017}
      - DB_NAME=${DB_NAME:-event-app-test}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_test_data:/data/db
    networks:
      - app-network
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongodb_test_data:

networks:
  app-network:
    driver: bridge 