FROM golang:1.24.1-alpine

# Install air for hot reloading
RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

EXPOSE 3001

# Run air for hot reloading
CMD ["air"] 