# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  lint:
    cmds:
      - golangci-lint run --config .golangci.yml
    silent: false
  format:
    cmds:
      - golangci-lint --config .golangci.yml
    silent: false
  docker-dev:
    cmds:
      - docker-compose -f docker-compose.dev.yml up
      - task: docker-dev-down
    silent: false
  docker-dev-down:
    cmds:
      - docker-compose -f docker-compose.dev.yml down
    silent: false
  docker-test:
    cmds:
      - docker-compose -f docker-compose.test.yml run --rm -e GIN_MODE=debug app-test go test -v -count=1 ./src/tests/e2e/...
      - task: docker-test-down
    silent: false
  docker-test-down:
    cmds:
      - docker-compose -f docker-compose.test.yml down
    silent: false
  tidy:
    cmds:
      - go mod tidy
    silent: false
