# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  lint:
    cmds:
      - golangci-lint run
    silent: false
  format:
    cmds:
      - golangci-lint fmt
    silent: false
